#!/usr/bin/env python3
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

IN_011 = ROOT / "artifacts/json/lift_twist_local_answer_cell_generator_theorem_011.v1.json"
IN_012 = ROOT / "artifacts/json/lift_twist_anchor_node_path_geometry_012.v1.json"

SECTION = ROOT / "paper/sections/08_local_answer_cell_theorem.tex"
MAIN = ROOT / "paper/main.tex"
OUT_JSON = ROOT / "artifacts/json/local_cell_theorem_section_013.v1.json"
OUT_NOTE = ROOT / "notes/local_cell_theorem_section_013.md"


def load_json(path):
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print("wrote", path)


def main():
    a011 = load_json(IN_011)
    a012 = load_json(IN_012)

    if not a011.get("theorem_pass"):
        raise SystemExit("011 theorem_pass is not true")
    if not a012.get("theorem_pass"):
        raise SystemExit("012 theorem_pass is not true")

    rows = a011["generated_rows"]

    table_lines = []
    for r in rows:
        c_path = " ".join(str(x) for x in r["c_path"])
        c_values = " ".join(str(x) for x in r["c_values"])
        anchor_residues = " ".join(str(x) for x in r["anchor_residues"])
        overlap = " ".join(str(x) for x in r["overlap"]) if r["overlap"] else "none"
        table_lines.append(
            f"{r['state']} & {r['shell_bit']} & {r['rank_bit']} & "
            f"{r['selected_candidate_index']} & {r['c_key']} & {r['anchor_key']} & "
            f"\\texttt{{{c_path}}} & \\texttt{{{c_values}}} & "
            f"\\texttt{{{anchor_residues}}} & \\texttt{{{overlap}}} \\\\"
        )

    section = r"""\section{Local Answer-Cell Generator Theorem}

The previous sections introduced Lift \& Twist as a coordinate-straightening mechanism.  The Project 22 audit sequence now gives a stronger local result: within the four-state reduced target, the answer-cell data are generated from two bits.

Let \(b\in\{0,1\}\) be the shell bit, with \(b=0\) for the ordinary shell and \(b=1\) for the branch shell.  Let \(r\in\{0,1\}\) be the rank bit.  The four local states are
\[
    O0=(0,0),\quad
    O1=(0,1),\quad
    B0=(1,0),\quad
    B1=(1,1).
\]

\begin{theorem}[Local Lift \& Twist answer-cell theorem]
For the four-state local answer-cell target, the state bits \(b,r\) generate the C row, anchor column, selected candidate, C key, anchor key, C path, C value set, anchor residue set, overlap markers, and closed anchor node path.  The generated table agrees exactly with the Project 22 target table.
\end{theorem}

\paragraph{Header laws.}
The visible placement and key data are generated by
\[
    c_{\mathrm{row}} = 2b+r,
\]
\[
    a_{\mathrm{col}} = 1+r+b(2r-1),
\]
\[
    s = 4c_{\mathrm{row}} + a_{\mathrm{col}},
\]
\[
    c_{\mathrm{key}} \equiv 11+6b+2r \pmod{15},
\]
\[
    a_{\mathrm{key}} \equiv 4b+12r+12br \pmod{15}.
\]

\paragraph{C-side path law.}
Let
\[
    d_1 \equiv 6-3b-3r+br \pmod{15},
\]
\[
    d_2 \equiv (1-b)(3+9r)+13b \pmod{15}.
\]
Then the C path is
\[
    [c_{\mathrm{key}},\ c_{\mathrm{key}}+d_1,\ c_{\mathrm{key}}+d_2,\ c_{\mathrm{key}}]\pmod{15}.
\]

\paragraph{Anchor-side residue law.}
The anchor key is \(a_{\mathrm{key}}\).  Ordinary states use offsets
\[
    \{5,7,12\}\cup\{1+3(1-r),\ 2+6(1-r),\ 3+6(1-r)\},
\]
while branch states use offsets
\[
    \{0,4\}\cup\{11-6r,\ 13-4r,\ 14-4r\},
\]
with an additional terminal offset \(12\) when \(r=1\).  Adding the appropriate offsets to \(a_{\mathrm{key}}\) modulo 15 gives the anchor residue set.

\paragraph{Closed anchor path law.}
The ordered anchor paths are generated by ordered offsets and shell-dependent lift masks.  Ordinary states use the open lift mask
\[
    [1,1,0,0,0,0],
\]
and branch states use the open lift mask
\[
    [0,0,0,1,0,1].
\]
The open path is then closed by returning to the first node-pair.

\paragraph{Generated target.}
\[
\begin{array}{c|c|c|c|c|c|c|c|c|c}
\mathrm{state} & b & r & s & c_{\mathrm{key}} & a_{\mathrm{key}} & C\ \mathrm{path} & C\ \mathrm{values} & A\ \mathrm{residues} & \mathrm{overlap}\\
\hline
""" + "\n".join(table_lines) + r"""
\end{array}
\]

Artifacts 007--012 verify these laws independently and then consolidate them.  Artifact 011 verifies that the generated rows match the local answer-cell target.  Artifact 012 verifies the closed anchor node path geometry.

\paragraph{Boundary.}
This theorem is local to the four-state reduced target.  It does not yet derive the full reduced 16-candidate universe from native G60 provenance.  It does not derive a full G60-native generator, and it does not close Gap A.
"""

    write(SECTION, section)

    main = MAIN.read_text(encoding="utf-8")
    include_line = r"\input{sections/08_local_answer_cell_theorem}"
    if include_line not in main:
        main = main.replace(
            r"\input{sections/07_conclusion}",
            include_line + "\n" + r"\input{sections/07_conclusion}",
        )
        write(MAIN, main)
    else:
        print("main already includes section 08")

    result = {
        "status": "local_cell_theorem_section_recorded",
        "audit_id": "013",
        "section": str(SECTION),
        "main": str(MAIN),
        "inputs": {
            "011": str(IN_011),
            "012": str(IN_012),
        },
        "project22_011_theorem_pass": bool(a011.get("theorem_pass")),
        "project22_012_theorem_pass": bool(a012.get("theorem_pass")),
        "main_contains_section": include_line in MAIN.read_text(encoding="utf-8"),
        "claim": "Wrote the local Lift & Twist answer-cell theorem into the paper.",
        "boundary": "The theorem is local to the four-state reduced target and does not close Gap A.",
    }

    write(OUT_JSON, json.dumps(result, indent=2, sort_keys=True) + "\n")

    note = """# Local cell theorem section 013

Status: local_cell_theorem_section_recorded

## Result

Wrote `paper/sections/08_local_answer_cell_theorem.tex` and wired it into `paper/main.tex`.

## Claim

The paper now records the local Lift & Twist answer-cell theorem: from bits b,r, the local cell generates the C row, anchor column, selected candidate, C key, anchor key, C path, C values, anchor residue set, overlap markers, and closed anchor node path.

## Boundary

The theorem is local to the four-state reduced target. It does not derive the full reduced 16-candidate universe from native G60 provenance and does not close Gap A.
"""
    write(OUT_NOTE, note)

    print("status", result["status"])
    print("main_contains_section", result["main_contains_section"])


if __name__ == "__main__":
    main()
